[package]
name = "ranim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cstr = "0.2.10"
glam = "0.20.5"

[workspace]
members = ["ranim-render"]
